<a href="https://colab.research.google.com/github/22f1000003/MLP-CODE/blob/main/Compare_data_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas, the compare() function provides a way to compare two DataFrame objects and generate a DataFrame highlighting the differences between them. This can be particularly useful when you have two datasets and want to identify discrepancies or changes between them

**DataFrame.compare(other, align_axis=1, keep_shape=False, keep_equal=False)**

So, let’s understand each of its parameters –

other : This is the first parameter which actually takes the DataFrame object to be compared with the present DataFrame.

align_axis : It deals with the axis(vertical / horizontal) where the comparison is to be made(by default False).0 or index : Here the output of the differences are presented vertically, 1 or columns : The output of the differences are displayed horizontally.

keep_shape : It means that whether we want all the data values to be displayed in the output or only the ones with distinct value. It is of bool type and the default value for it is “false”, i.e. it displays all the values in the table by default.

keep_equal : This is mainly for displaying same or equal values in the output when set to True. If it is made false then it will display the equal values as NANs.

Returns another DataFrame with the differences between the two dataFrames.

Let's create dataframe and see how compare works.

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "col1": ["a", "a", "b", "b", "a"],
        "col2": [1.0, 2.0, 3.0, np.nan, 5.0],
        "col3": [1.0, 2.0, 3.0, 4.0, 5.0],
    },
    columns=["col1", "col2", "col3"],
)

print(df)

  col1  col2  col3
0    a   1.0   1.0
1    a   2.0   2.0
2    b   3.0   3.0
3    b   NaN   4.0
4    a   5.0   5.0

In [2]:
df2 = df.copy()

In [3]:
df.compare(df2)
# it is not generate any things here is not any discrepencies

Empty DataFrame
Columns: []
Index: []

In [7]:
df2.loc[0,'col1'] = 'c'
df2.loc[2,'col3'] = 42

In [8]:
df2

  col1  col2  col3
0    c   1.0   1.0
1    a   2.0   2.0
2    b   3.0  42.0
3    b   NaN   4.0
4    a   5.0   5.0

In [9]:
df.compare(df2)

  col1       col3
  self other self other
0    a     c  NaN   NaN
2  NaN   NaN  3.0  42.0

In [10]:
df.compare(df2,align_axis=0)

        col1  col3
0 self     a   NaN
  other    c   NaN
2 self   NaN   3.0
  other  NaN  42.0