<a href="https://colab.research.google.com/github/22f1000003/MLP-CODE/blob/main/satyam_Introduction_to__pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is my**first experience** with the colab
the following is the list
* Item 1
* Item 2
   * subitem 1
   * subitem2

1.   List item
2.   List item
$$ v = w0 + w1×1$$

In [119]:

import pandas as pd
pd.__version__

'2.2.2'

The primary data structure in pandas are implemented as two classes:
* DataFrame. which you can imagin as a relational data table with rows and named columns.
*Series. which is a single column. Each row can be labled via an index. A DataFrame contains one or more Series and a name for each series.
The data frame is a commonly used abstration for data manipulation. similar implimentations exist in Sparkand R.

In [120]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes(as_frame=True)
print(type(diabetes['data']))
print(diabetes.data_filename)

<class 'pandas.core.frame.DataFrame'>
diabetes_data_raw.csv.gz

In [121]:
df = diabetes['data']

In [122]:
print(diabetes.keys())

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

*Creating pandas dataframe from Series*

In [123]:
cities = pd.Series(['delhi','Bengalore', 'Chennai','kanpur'])
population = pd.Series([17000000, 12000000, 6000000,])

**A DataFrame in pandas is:

👉 like a dictionary of columns (Series), where each column is like an array**

In [124]:
city_info_df = pd.DataFrame({'City': cities, "Population": population})

In [125]:
type(city_info_df)

pandas.core.frame.DataFrame

In [126]:
city_info_df

        City  Population
0      delhi  17000000.0
1  Bengalore  12000000.0
2    Chennai   6000000.0
3     kanpur         NaN

In [127]:
city_info_df.head()

        City  Population
0      delhi  17000000.0
1  Bengalore  12000000.0
2    Chennai   6000000.0
3     kanpur         NaN

In [128]:
import psutil
print(f"Cloud RAM used: {psutil.virtual_memory().percent}%")

Cloud RAM used: 12.8%

**Eploring Data in DataFrame**

Quikly examine few entries in the DataFrame. Say first five 5 and last 5.

In [129]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [130]:
df.tail()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [131]:
? df.head

In [132]:
df.head(n=5)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [133]:
df.tail(n=3)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

Find out number of rows and column in the dataframe

In [134]:
df.shape

(442, 10)

how to see the names of the columns

In [135]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [136]:
list(df.columns)

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [137]:
?load_diabetes

In [138]:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

**Lecture-3**

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

let's get summary statistics on the dataframe

In [140]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [141]:
df.describe(percentiles= [0.2,0.3,0.5,0.6,0.8])

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
20%,-4.547248e-02,-4.464164e-02,-4.048038e-02,-4.009893e-02,-3.871969e-02,-3.695017e-02,-3.971921e-02,-3.949338e-02,-4.117617e-02,-3.835666e-02
30%,-2.730979e-02,-4.464164e-02,-2.991782e-02,-2.873752e-02,-2.633611e-02,-2.480001e-02,-2.867429e-02,-3.949338e-02,-2.796492e-02,-2.468771e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
60%,1.628068e-02,5.068012e-02,5.218854e-03,8.100982e-03,8.062710e-03,8.706873e-03,8.142084e-03,-2.592262e-03,1.255119e-02,7.206516e-03
80%,4.170844e-02,5.068012e-02,4.229559e-02,4.941519e-02,3.943444e-02,3.952068e-02,3.759519e-02,3.430886e-02,3.885335e-02,3.620126e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

here we transpose it by using T attribute so it is become more readeable

In [142]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,442.0,-2.511817e-19,0.047619,-0.107226,-0.037299,0.005383,0.038076,0.110727
sex,442.0,1.230790e-17,0.047619,-0.044642,-0.044642,-0.044642,0.050680,0.050680
bmi,442.0,-2.245564e-16,0.047619,-0.090275,-0.034229,-0.007284,0.031248,0.170555
bp,442.0,-4.797570e-17,0.047619,-0.112399,-0.036656,-0.005670,0.035644,0.132044
s1,442.0,-1.381499e-17,0.047619,-0.126781,-0.034248,-0.004321,0.028358,0.153914
s2,442.0,3.918434e-17,0.047619,-0.115613,-0.030358,-0.003819,0.029844,0.198788
s3,442.0,-5.777179e-18,0.047619,-0.102307,-0.035117,-0.006584,0.029312,0.181179
s4,442.0,-9.042540e-18,0.047619,-0.076395,-0.039493,-0.002592,0.034309,0.185234
s5,442.0,9.293722e-17,0.047619,-0.126097,-0.033246,-0.001947,0.032432,0.133597
s6,442.0,1.130318e-17,0.047619,-0.137767,-0.033179,-0.001078,0.027917,0.135612

**Selection of particular column s and its attribute and i can say here geting series**

In [143]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [144]:
df['age']

0      0.038076
1     -0.001882
2      0.085299
3     -0.089063
4      0.005383
         ...
437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, Length: 442, dtype: float64

In [145]:
type(df['age'])

pandas.core.series.Series

how to find particular value in particular series

In [146]:
df['age'][0]

np.float64(0.038075906433423026)

In [147]:
df['age'][:5]

0    0.038076
1   -0.001882
2    0.085299
3   -0.089063
4    0.005383
Name: age, dtype: float64

In [148]:
df['age'][-5:]

437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, dtype: float64

In [149]:
df['age'][100:200]

100    0.016281
101    0.016281
102   -0.092695
103    0.059871
104   -0.027310
         ...
195    0.027178
196   -0.023677
197    0.048974
198   -0.052738
199    0.041708
Name: age, Length: 100, dtype: float64

In [150]:
df[['age','sex']]

          age       sex
0    0.038076  0.050680
1   -0.001882 -0.044642
2    0.085299  0.050680
3   -0.089063 -0.044642
4    0.005383 -0.044642
..        ...       ...
437  0.041708  0.050680
438 -0.005515  0.050680
439  0.041708  0.050680
440 -0.045472 -0.044642
441 -0.045472 -0.044642

[442 rows x 2 columns]

In [151]:
df[['age','sex']][:5]

        age       sex
0  0.038076  0.050680
1 -0.001882 -0.044642
2  0.085299  0.050680
3 -0.089063 -0.044642
4  0.005383 -0.044642

In [152]:
df[['age','sex']][-5:]

          age       sex
437  0.041708  0.050680
438 -0.005515  0.050680
439  0.041708  0.050680
440 -0.045472 -0.044642
441 -0.045472 -0.044642

*'''loc'' location
*'''iloc'' integer location

*   List item
*   List item in the iloc i give specified integer so it  give that which is associated with
* 1. loc → Label-based selection
Uses row/column names (labels)
Works with index names and column names
* **iloc → Integer LOcation**

In [153]:
df.iloc[0]
# it gives first row in this dataframe

age    0.038076
sex    0.050680
bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
s4    -0.002592
s5     0.019907
s6    -0.017646
Name: 0, dtype: float64

In [154]:
df.head(n=4)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362

In [155]:
df.loc[0 ,'age']

np.float64(0.038075906433423026)

in the loc specified lable of the row

In [156]:
df.loc[0,'sex']

np.float64(0.05068011873981862)

iloc position of the data in the row note here only uses integer it is similar to access from array
and in the loc is similar to access to like dictionary

In [157]:
df.iloc[0 , 2:7]
# first interies is equal to row second interies is equal to accessing column

bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
Name: 0, dtype: float64

In [158]:
df.loc[3,['age','sex']]

age   -0.089063
sex   -0.044642
Name: 3, dtype: float64

In [159]:
age_df = df.loc[df.age<5.383060e-03]

In [160]:
age_df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504
...,...,...,...,...,...,...,...,...,...,...
435,-0.012780,-0.044642,-0.023451,-0.040099,-0.016704,0.004636,-0.017629,-0.002592,-0.038460,-0.038357
436,-0.056370,-0.044642,-0.074108,-0.050427,-0.024960,-0.047034,0.092820,-0.076395,-0.061176,-0.046641
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [161]:
age_df.iloc[0]

age   -0.001882
sex   -0.044642
bmi   -0.051474
bp    -0.026328
s1    -0.008449
s2    -0.019163
s3     0.074412
s4    -0.039493
s5    -0.068332
s6    -0.092204
Name: 1, dtype: float64

below the code is give key error because in loc we put lable data which is in age_df
it work like dict key but iloc is not give error if i put 2 index because it access as integer

In [162]:
#age_df.loc[2]
# 2 lable is not present in Age_df

In [163]:
age_df.iloc[2]

age   -0.092695
sex   -0.044642
bmi   -0.040696
bp    -0.019442
s1    -0.068991
s2    -0.079288
s3     0.041277
s4    -0.076395
s5    -0.041176
s6    -0.096346
Name: 5, dtype: float64

**Lecture-4** Data selection using pandas | part 2

In [164]:
import numpy as np

In [165]:
df = pd.DataFrame(np.random.rand(9,4), index=list("abcdefghi"),columns=list('ABCD'))

In [166]:
df.shape

(9, 4)

In [167]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, a to i
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       9 non-null      float64
 1   B       9 non-null      float64
 2   C       9 non-null      float64
 3   D       9 non-null      float64
dtypes: float64(4)
memory usage: 360.0+ bytes

In [169]:
df.head()

          A         B         C         D
a  0.161841  0.511091  0.359386  0.342688
b  0.738959  0.264272  0.576123  0.766790
c  0.632134  0.144640  0.094014  0.131022
d  0.286187  0.345775  0.129429  0.107348
e  0.906380  0.892225  0.136642  0.771987

In [170]:
another_df = pd.DataFrame(
    np.random.rand(100,4),
    index=range(10,110),
    columns=list('abcd')
)

In [171]:
another_df.head()

           a         b         c         d
10  0.067501  0.984127  0.685376  0.660010
11  0.534615  0.615179  0.887074  0.842012
12  0.315562  0.259133  0.810243  0.384122
13  0.100841  0.861451  0.659042  0.573381
14  0.571424  0.862931  0.248790  0.879790

In [172]:
another_df.tail()

            a         b         c         d
105  0.591993  0.627761  0.595497  0.363394
106  0.375988  0.848007  0.771515  0.717381
107  0.678752  0.121453  0.217679  0.441809
108  0.395702  0.424901  0.046610  0.640477
109  0.020096  0.357490  0.801797  0.688047

In [173]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='object')

In [174]:
#df.loc[0]
# because in df 0 is not present but a is present

In [175]:
df.loc['a']

A    0.161841
B    0.511091
C    0.359386
D    0.342688
Name: a, dtype: float64

In [176]:
df.loc['a','B':'D']

B    0.511091
C    0.359386
D    0.342688
Name: a, dtype: float64

In [177]:
df.iloc[0:4,:]

          A         B         C         D
a  0.161841  0.511091  0.359386  0.342688
b  0.738959  0.264272  0.576123  0.766790
c  0.632134  0.144640  0.094014  0.131022
d  0.286187  0.345775  0.129429  0.107348

In [178]:
df.iloc[:,1]

a    0.511091
b    0.264272
c    0.144640
d    0.345775
e    0.892225
f    0.457186
g    0.255758
h    0.827793
i    0.426984
Name: B, dtype: float64

lambda function which is use directly do not need to define function

In [179]:
selector = lambda df: df['A']>0

In [180]:
selector

In [181]:
df.loc[selector]

          A         B         C         D
a  0.161841  0.511091  0.359386  0.342688
b  0.738959  0.264272  0.576123  0.766790
c  0.632134  0.144640  0.094014  0.131022
d  0.286187  0.345775  0.129429  0.107348
e  0.906380  0.892225  0.136642  0.771987
f  0.397912  0.457186  0.861587  0.956730
g  0.160786  0.255758  0.858602  0.847728
h  0.972820  0.827793  0.602404  0.962572
i  0.197391  0.426984  0.837027  0.271242

In [182]:
selector = lambda df: df['A']>0.6

In [183]:
selector

In [184]:
df.loc[selector]

          A         B         C         D
b  0.738959  0.264272  0.576123  0.766790
c  0.632134  0.144640  0.094014  0.131022
e  0.906380  0.892225  0.136642  0.771987
h  0.972820  0.827793  0.602404  0.962572

In [185]:
selctor = lambda df: (df['A']>0.6) & (df['B']<0.7)

In [186]:
selctor

In [187]:
df.loc[selctor]

          A         B         C         D
b  0.738959  0.264272  0.576123  0.766790
c  0.632134  0.144640  0.094014  0.131022

In [188]:
condition_for_selector = (df['A']>0.5) & (df['B']<0.7)

In [189]:
df[condition_for_selector]

          A         B         C         D
b  0.738959  0.264272  0.576123  0.766790
c  0.632134  0.144640  0.094014  0.131022

In [190]:
condition_for_selector

a    False
b     True
c     True
d    False
e    False
f    False
g    False
h    False
i    False
dtype: bool

**week-1 LECTURE_5 : Drop in dataframe::**

**Adding a column inthe Dateframe**

Creating a new column E in my DataFrame df

np.random.rand.(9)
*   List item This comes from NumPy
*   List item 👉 It generates:

9 random numbers

Between 0 and 1

In [191]:
df['E'] = np.random.rand(9)

In [192]:
df.head()

          A         B         C         D         E
a  0.161841  0.511091  0.359386  0.342688  0.613409
b  0.738959  0.264272  0.576123  0.766790  0.536549
c  0.632134  0.144640  0.094014  0.131022  0.392243
d  0.286187  0.345775  0.129429  0.107348  0.311262
e  0.906380  0.892225  0.136642  0.771987  0.550874

In [193]:
df['F'] = np.random.rand(9)*10

In [194]:
df.head()

          A         B         C         D         E         F
a  0.161841  0.511091  0.359386  0.342688  0.613409  6.735626
b  0.738959  0.264272  0.576123  0.766790  0.536549  6.528359
c  0.632134  0.144640  0.094014  0.131022  0.392243  9.737165
d  0.286187  0.345775  0.129429  0.107348  0.311262  5.756694
e  0.906380  0.892225  0.136642  0.771987  0.550874  2.861807

In [195]:
df['G'] = df['E'] + df['F']

In [196]:
df

          A         B         C         D         E         F          G
a  0.161841  0.511091  0.359386  0.342688  0.613409  6.735626   7.349035
b  0.738959  0.264272  0.576123  0.766790  0.536549  6.528359   7.064909
c  0.632134  0.144640  0.094014  0.131022  0.392243  9.737165  10.129409
d  0.286187  0.345775  0.129429  0.107348  0.311262  5.756694   6.067956
e  0.906380  0.892225  0.136642  0.771987  0.550874  2.861807   3.412681
f  0.397912  0.457186  0.861587  0.956730  0.947544  2.563519   3.511063
g  0.160786  0.255758  0.858602  0.847728  0.452810  2.870200   3.323010
h  0.972820  0.827793  0.602404  0.962572  0.255798  8.381157   8.636955
i  0.197391  0.426984  0.837027  0.271242  0.364769  2.610304   2.975073

In [197]:
criteria = df['A']<0.2

In [198]:
criteria

a     True
b    False
c    False
d    False
e    False
f    False
g     True
h    False
i     True
Name: A, dtype: bool

here you can see only one value is true

In [199]:
df.loc[criteria,'A']

a    0.161841
g    0.160786
i    0.197391
Name: A, dtype: float64

In [200]:
df

          A         B         C         D         E         F          G
a  0.161841  0.511091  0.359386  0.342688  0.613409  6.735626   7.349035
b  0.738959  0.264272  0.576123  0.766790  0.536549  6.528359   7.064909
c  0.632134  0.144640  0.094014  0.131022  0.392243  9.737165  10.129409
d  0.286187  0.345775  0.129429  0.107348  0.311262  5.756694   6.067956
e  0.906380  0.892225  0.136642  0.771987  0.550874  2.861807   3.412681
f  0.397912  0.457186  0.861587  0.956730  0.947544  2.563519   3.511063
g  0.160786  0.255758  0.858602  0.847728  0.452810  2.870200   3.323010
h  0.972820  0.827793  0.602404  0.962572  0.255798  8.381157   8.636955
i  0.197391  0.426984  0.837027  0.271242  0.364769  2.610304   2.975073

In [201]:
cities = ['satyam','aman','aditay','dsfds','dfsd','dfsf',
          'erwer','safas','sfaf']

In [202]:
df['city'] = cities

In [203]:
df

,A,B,C,D,E,F,G,city
a,0.161841,0.511091,0.359386,0.342688,0.613409,6.735626,7.349035,satyam
b,0.738959,0.264272,0.576123,0.766790,0.536549,6.528359,7.064909,aman
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd
f,0.397912,0.457186,0.861587,0.956730,0.947544,2.563519,3.511063,dfsf
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer
h,0.972820,0.827793,0.602404,0.962572,0.255798,8.381157,8.636955,safas
i,0.197391,0.426984,0.837027,0.271242,0.364769,2.610304,2.975073,sfaf

In [204]:
criteria = df['city'].isin(['satyam','aman','sfaf'])

In [205]:
criteria

a     True
b     True
c    False
d    False
e    False
f    False
g    False
h    False
i     True
Name: city, dtype: bool

In [206]:
cities_new = ['satyam','aman','aditay','madhav','shuryans','dfsf',
          'erwer','safas','sfaf']

In [207]:
df['new_city'] = cities_new

In [208]:
df

,A,B,C,D,E,F,G,city,new_city
a,0.161841,0.511091,0.359386,0.342688,0.613409,6.735626,7.349035,satyam,satyam
b,0.738959,0.264272,0.576123,0.766790,0.536549,6.528359,7.064909,aman,aman
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay,aditay
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds,madhav
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd,shuryans
f,0.397912,0.457186,0.861587,0.956730,0.947544,2.563519,3.511063,dfsf,dfsf
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer,erwer
h,0.972820,0.827793,0.602404,0.962572,0.255798,8.381157,8.636955,safas,safas
i,0.197391,0.426984,0.837027,0.271242,0.364769,2.610304,2.975073,sfaf,sfaf

In [209]:
df_copy = df.copy()

In [210]:
df

,A,B,C,D,E,F,G,city,new_city
a,0.161841,0.511091,0.359386,0.342688,0.613409,6.735626,7.349035,satyam,satyam
b,0.738959,0.264272,0.576123,0.766790,0.536549,6.528359,7.064909,aman,aman
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay,aditay
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds,madhav
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd,shuryans
f,0.397912,0.457186,0.861587,0.956730,0.947544,2.563519,3.511063,dfsf,dfsf
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer,erwer
h,0.972820,0.827793,0.602404,0.962572,0.255798,8.381157,8.636955,safas,safas
i,0.197391,0.426984,0.837027,0.271242,0.364769,2.610304,2.975073,sfaf,sfaf

In [211]:
df_copy

,A,B,C,D,E,F,G,city,new_city
a,0.161841,0.511091,0.359386,0.342688,0.613409,6.735626,7.349035,satyam,satyam
b,0.738959,0.264272,0.576123,0.766790,0.536549,6.528359,7.064909,aman,aman
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay,aditay
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds,madhav
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd,shuryans
f,0.397912,0.457186,0.861587,0.956730,0.947544,2.563519,3.511063,dfsf,dfsf
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer,erwer
h,0.972820,0.827793,0.602404,0.962572,0.255798,8.381157,8.636955,safas,safas
i,0.197391,0.426984,0.837027,0.271242,0.364769,2.610304,2.975073,sfaf,sfaf

In [212]:
criteria = df_copy['city'].isin(['satyam','aman','aditay'])

In [213]:
criteria

a     True
b     True
c     True
d    False
e    False
f    False
g    False
h    False
i    False
Name: city, dtype: bool

**how to update the value the column**

In [214]:
df_copy.loc[df.city == 'satyam', 'city'] = 'satyam_new'

In [215]:
df_copy

,A,B,C,D,E,F,G,city,new_city
a,0.161841,0.511091,0.359386,0.342688,0.613409,6.735626,7.349035,satyam_new,satyam
b,0.738959,0.264272,0.576123,0.766790,0.536549,6.528359,7.064909,aman,aman
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay,aditay
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds,madhav
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd,shuryans
f,0.397912,0.457186,0.861587,0.956730,0.947544,2.563519,3.511063,dfsf,dfsf
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer,erwer
h,0.972820,0.827793,0.602404,0.962572,0.255798,8.381157,8.636955,safas,safas
i,0.197391,0.426984,0.837027,0.271242,0.364769,2.610304,2.975073,sfaf,sfaf

In [216]:
?df_copy.dorp

Object `df_copy.dorp` not found.

here we drop column

In [217]:
df_copy.drop(['new_city'],axis=1)
# axis = 1 means do operation on the column and if axis = 0 it means operation on the row

,A,B,C,D,E,F,G,city
a,0.161841,0.511091,0.359386,0.342688,0.613409,6.735626,7.349035,satyam_new
b,0.738959,0.264272,0.576123,0.766790,0.536549,6.528359,7.064909,aman
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd
f,0.397912,0.457186,0.861587,0.956730,0.947544,2.563519,3.511063,dfsf
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer
h,0.972820,0.827793,0.602404,0.962572,0.255798,8.381157,8.636955,safas
i,0.197391,0.426984,0.837027,0.271242,0.364769,2.610304,2.975073,sfaf

In [218]:
df_copy = df_copy.drop(['i'])

In [219]:
df_copy

,A,B,C,D,E,F,G,city,new_city
a,0.161841,0.511091,0.359386,0.342688,0.613409,6.735626,7.349035,satyam_new,satyam
b,0.738959,0.264272,0.576123,0.766790,0.536549,6.528359,7.064909,aman,aman
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay,aditay
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds,madhav
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd,shuryans
f,0.397912,0.457186,0.861587,0.956730,0.947544,2.563519,3.511063,dfsf,dfsf
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer,erwer
h,0.972820,0.827793,0.602404,0.962572,0.255798,8.381157,8.636955,safas,safas

In [220]:
?df_copy.sample

In [221]:
df.sample(3)

,A,B,C,D,E,F,G,city,new_city
a,0.161841,0.511091,0.359386,0.342688,0.613409,6.735626,7.349035,satyam,satyam
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds,madhav
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay,aditay

In [222]:
df_copy.sample(3)

,A,B,C,D,E,F,G,city,new_city
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer,erwer
h,0.972820,0.827793,0.602404,0.962572,0.255798,8.381157,8.636955,safas,safas
f,0.397912,0.457186,0.861587,0.956730,0.947544,2.563519,3.511063,dfsf,dfsf

random
-state it stop sample generation radomly after this it generate same sample

In [223]:
df.sample(3,random_state=78)

,A,B,C,D,E,F,G,city,new_city
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds,madhav
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay,aditay
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd,shuryans

In [224]:
df.sample(3,random_state=78)

,A,B,C,D,E,F,G,city,new_city
d,0.286187,0.345775,0.129429,0.107348,0.311262,5.756694,6.067956,dsfds,madhav
c,0.632134,0.144640,0.094014,0.131022,0.392243,9.737165,10.129409,aditay,aditay
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd,shuryans

In [225]:
df_copy.sample(3,replace = True)

,A,B,C,D,E,F,G,city,new_city
e,0.906380,0.892225,0.136642,0.771987,0.550874,2.861807,3.412681,dfsd,shuryans
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer,erwer
g,0.160786,0.255758,0.858602,0.847728,0.452810,2.870200,3.323010,erwer,erwer

**DataFrame.sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None, ignore_index=False)**
these are following attribute of sample function
1. n👉 Number of rows to select
2. frac👉 Fraction (percentage) of data
3. replace👉 Allow repetition or not
False → no repeat (default)
True → repeat allowed
4. weights👉 Probability for each row
5. random_state👉 Fix randomness (for same result every time)
6. axis👉 Sample rows or columns
0 → rows (default)
1 → columns
ignore_index
👉 Reset index or not

**W1_L6: Apply statistics using pandas**

In [26]:
import pandas as pd
cities = ['Mumbai','Chennai','Pune','Ahmedabad','Kolkata','Kanpur', 'Delhi']
city_df = pd.DataFrame(cities)

In [27]:
city_df.columns = ['city_name']

In [28]:
city_df

   city_name
0     Mumbai
1    Chennai
2       Pune
3  Ahmedabad
4    Kolkata
5     Kanpur
6      Delhi

In [29]:
condition = city_df.city_name == 'Mumbai'

In [30]:
condition

0     True
1    False
2    False
3    False
4    False
5    False
6    False
Name: city_name, dtype: bool

In [31]:
type(condition)

pandas.core.series.Series

In [32]:
city_df[condition]

  city_name
0    Mumbai

In [33]:
city_df[city_df.city_name == 'Pune']

  city_name
2      Pune

**Aggregation and grouping**

In [34]:
import numpy as np

In [35]:
random_state = np.random.RandomState(20)
random_series = pd.Series(random_state.randn(10))

In [41]:
random_series

0    0.883893
1    0.195865
2    0.357537
3   -2.343262
4   -1.084833
5    0.559696
6    0.939469
7   -0.978481
8    0.503097
9    0.406414
dtype: float64

**Now that the series is created, we can try aggregation function like mean,
std etc.**

In [42]:
random_series.mean()

np.float64(-0.05606039362719746)

In [45]:
random_series.std()

1.0622481307589278

In [47]:
random_series.sum()

np.float64(-0.5606039362719746)

**let's created s dataframe with 5 rows adn 2 columns contaning random number**

In [51]:
df = pd.DataFrame({'A':random_state.rand(5), 'B':random_state.rand(5)})

In [52]:
df

          A         B
0  0.770252  0.497940
1  0.492381  0.679411
2  0.631253  0.650786
3  0.839498  0.268795
4  0.461039  0.067325

In [53]:
df.sum()

A    3.194423
B    2.164257
dtype: float64

In [57]:
df.mean()

A    0.638885
B    0.432851
dtype: float64

**Try these operation row_wise**

In [60]:
df.mean(axis=1)

0    0.634096
1    0.585896
2    0.641019
3    0.554147
4    0.264182
dtype: float64

In [61]:
df.sum(axis=1)

0    1.268192
1    1.171792
2    1.282039
3    1.108293
4    0.528364
dtype: float64

## Groupby
**Split **- we split datafram into smaller dataframe based on the value of keys
**Apply** - we apply desired
aggregation/trandsformation on each dataframe
**Combine**- we combine result from apply state into a datafram

In [63]:
df = pd.DataFrame({'key':['A','B','C']*2, #
                   'data': range(6)})

In [65]:
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [66]:
df.groupby('key').sum()

     data
key
A       3
B       5
C       7